mgt:
    resource: "@MGTBundle/Resources/config/routing.yml"
    prefix:   /

ricms:
    resource: "@RICMSBundle/Resources/config/routing.yml"
    prefix:   /ricms

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"