ricms_livro:
    resource: "@RICMSBundle/Resources/config/routing/livro.yml"
    prefix:   /livro

ricms_livro_admin:
    resource: "@RICMSBundle/Resources/config/routing/livro_admin.yml"
    prefix:   /admin/livro

ricms_capitulo:
    resource: "@RICMSBundle/Resources/config/routing/capitulo.yml"
    prefix:   /capitulo
    
ricms_titulo_admin:
    resource: "@RICMSBundle/Resources/config/routing/titulo_admin.yml"
    prefix:   /admin/titulo

ricms_homepage:
    path:     /
    defaults: { _controller: RICMSBundle:Default:index }
    
ricms_about:
    path:     /sobre
    defaults: { _controller: RICMSBundle:Default:about }
