<?php

namespace MG\RICMS\RICMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CapituloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapituloRepository extends EntityRepository
{
}
