<?php

namespace MG\RICMS\RICMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LivroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivroRepository extends EntityRepository
{
}
