livro:
    path:     /
    defaults: { _controller: "RICMSBundle:Livro:index" }

livro_show:
    path:     /{id}/show
    defaults: { _controller: "RICMSBundle:Livro:show" }

livro_new:
    path:     /new
    defaults: { _controller: "RICMSBundle:Livro:new" }

livro_create:
    path:     /create
    defaults: { _controller: "RICMSBundle:Livro:create" }
    requirements: { _method: post }

livro_edit:
    path:     /{id}/edit
    defaults: { _controller: "RICMSBundle:Livro:edit" }

livro_update:
    path:     /{id}/update
    defaults: { _controller: "RICMSBundle:Livro:update" }
    requirements: { _method: post|put }

livro_delete:
    path:     /{id}/delete
    defaults: { _controller: "RICMSBundle:Livro:delete" }
    requirements: { _method: post|delete }
